# Generated by Django 3.2.7 on 2021-12-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=8, null=True),
        ),
    ]
