spring:
  port: 8080
  datasource:
  #     url: jdbc:h2:tcp://localhost/~/profile
  #     username: sa
  #     password:
  #     driver-class-name: org.h2.Driver
  #    url: jdbc:mysql://localhost:33060/profile-db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  #    username: user
  #    password: 1234
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    database-platform: org
  #  #     url: jdbc:h2:tcp://localhost/~/profile
  #  #     username: sa
  #  #     password:
  #  #     driver-class-name: org.h2.Driver
  #  #    url: jdbc:mysql://localhost:33060/profile-db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  #  #    username: user
  #  #    password: 1234
  #  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #  #    database-platform: org.hibernate.dialect.MySQL5Dialect.hibernate.dialect.MySQL5Dialect

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
  #  org.hibernate.type: trace
  session:
    storage-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  spring:
    profiles:
      active: local