# Generated by Django 3.2.7 on 2022-03-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(db_column='company_id', primary_key=True, serialize=False)),
                ('stock_name', models.CharField(blank=True, db_column='stock_name', help_text='종목명', max_length=200, null=True)),
                ('stock_code', models.CharField(blank=True, db_column='stock_code', help_text='종목코드', max_length=200, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, db_column='date', help_text='거래일', max_length=32, null=True)),
                ('close', models.FloatField(blank=True, db_column='close', help_text='종가', null=True)),
                ('open', models.FloatField(blank=True, db_column='open', help_text='시가', null=True)),
                ('high', models.FloatField(blank=True, db_column='high', help_text='고가', null=True)),
                ('low', models.FloatField(blank=True, db_column='low', help_text='저가', null=True)),
                ('volume', models.IntegerField(blank=True, db_column='volume', help_text='거래량', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockinfo', to='stockapp.company')),
            ],
            options={
                'db_table': 'stockinfo',
            },
        ),
    ]
