# Generated by Django 3.2.7 on 2022-02-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
