version: "3.3"
services:
  crawling-service:
    image: crawling
    ports:
      - 8001:8000
    volumes:
      - ./:/home/crawling
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - test
    entrypoint: ["bash", "-c"]
    restart: always
    command: 
      - |
        python manage.py makemigrations --noinput --settings=config.settings.local
        python manage.py migrate --noinput --settings=config.settings.local
        python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local
  
networks:
  test:
    external: true
