version: "3.3"
services:
#  investment-service:
#    image: investment-service
#    volumes:
#      - .:/home/spring
#    ports:
#      - 8080:8080
#      - 8090:8090
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://investment-database:3306/investment-db?useUnicode=true&serverTimezone=Asia/Seoul
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: 1234
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#      SPRING_DATASOURCE_DATABASE_PLATFORM: org.hibernate.dialect.MySQL5Dialect
#      SPRING_REDIS.HOST: redis
#    depends_on:
#      - investment-database
#      - investment-redis
#    restart: always
#    networks:
#      - test
#    entrypoint: ["bash", "-c"]
#    command:
#      - |
#        ./gradlew build
#        ./gradlew bootRun

  # investment-database:
  #   image: mysql:5.7
  #   ports:
  #     - 33061:3306
  #   environment:
  #     MYSQL_DATABASE: investment-db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: 1234
  #     MYSQL_ROOT_PASSWORD: 1234
  #   networks:
  #     - test
  #   command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  
  investment-redis:
    image: redis:6.2.6
    ports:
      - 63790:6379
    networks:
      - test
    command: [ "redis-server", "--protected-mode", "no" ]


networks:
  test:
    external: true